name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant permission to push to the repository (needed for gh-pages)
    steps:
      # Checkout the code from GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js for the build process
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies for the whole monorepo
      - name: Install dependencies
        run: |
          npm install

      # Build the packages in the monorepo
      - name: Build packages
        run: lerna run build  # This will run the 'build' script in each package

      - name: Copy built websites into top-level dist package
        run: |
          cp -R packages/clinic-website-template/ dist/clinic
          cp -R packages/doctors-appointment/dist dist/dokto
          mkdir -p dist/tailwind/keynote && cp -R packages/keynote/out/* dist/tailwind/keynote
          mkdir -p dist/tailwind/studio && cp -R packages/studio/out/* dist/tailwind/studio
          # mkdir -p dist/tailwind/radiant && cp -R packages/radiant/.next/* dist/tailwind/radiant
          # mkdir -p dist/tailwind/spotlight && cp -R packages/spotlight/.next/* dist/tailwind/spotlight
      # Deploy the built packages to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides a token to authenticate
          publish_dir: './dist'  # Specify the dist directory in each package
